-name : frontend App
 hosts : All
 tasks : 
  -name : Install nginx
  ansoble.builtin.dnf:
  name : nginx
  state : latest

  - name: Make sure a service unit is running
     ansible.builtin.systemd_service:
        state: start
        name: nginx
